
services:
  oracle-nginx:
    build:
      context: .
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    ports:
      - "8080:80"
    volumes:
      - ./logs:/var/log/nginx
    environment:
      - NGINX_LOG_LEVEL=${NGINX_LOG_LEVEL}
    restart: unless-stopped
